<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO6fqsi9\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO6fqsi9/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerO6fqsi9.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerO6fqsi9\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerO6fqsi9\appProdProjectContainer([
    'container.build_hash' => 'O6fqsi9',
    'container.build_id' => 'f11be17e',
    'container.build_time' => 1551355874,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO6fqsi9');
